"""Alembic upgrade/downgrade round-trip integration test (D-11 lock).

Proves the initial migration generated by Plan 06-02 is reversible against an
empty DB:

1. ``alembic upgrade head`` — schema appears (user, conversation, message, the
   composite ``message_conv_seq`` unique index).
2. ``alembic downgrade base`` — schema disappears (only ``alembic_version``
   remains).
3. ``alembic upgrade head`` — schema reappears identical to step 1.

This is the gate for D-11: ``just migrate`` (Plan 06-06) executes the same
``alembic upgrade head`` against the compose db, so a working round-trip here
is what lets Plans 03/04/06 build clean DB state for their fixtures.

Path-based selection (CLAUDE.md): the file lives under ``tests/integration/db/``
so ``just test-integration`` picks it up; no ``@pytest.mark.integration``.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

# `backend/` — the directory that contains alembic.ini. ``cwd`` for every
# alembic subprocess. Resolved from this file's location so the test does not
# care where pytest is invoked from.
_BACKEND_DIR = Path(__file__).resolve().parents[3]


def _run_alembic(args: list[str], database_url: str) -> subprocess.CompletedProcess[str]:
    """Run ``uv run alembic …`` with ``DATABASE_URL`` env override.

    Returns the completed process so the caller can assert against returncode
    and stderr/stdout — fail-loud if migrations error.
    """
    env = {**os.environ, "DATABASE_URL": database_url}
    return subprocess.run(  # noqa: S603 (trusted args; no shell)
        ["uv", "run", "alembic", *args],
        cwd=_BACKEND_DIR,
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )


async def _public_tables(database_url: str) -> set[str]:
    """Return the set of tables in the ``public`` schema."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as conn:
            result = await conn.execute(
                text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'"),
            )
            return {row[0] for row in result}
    finally:
        await engine.dispose()


async def _public_indexes(database_url: str) -> set[str]:
    """Return the set of indexes in the ``public`` schema."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as conn:
            result = await conn.execute(
                text("SELECT indexname FROM pg_indexes WHERE schemaname = 'public'"),
            )
            return {row[0] for row in result}
    finally:
        await engine.dispose()


async def test_alembic_upgrade_downgrade_round_trip(pg_database_url: str) -> None:
    """upgrade head → downgrade base → upgrade head; assert schema each step."""
    # Step 1 — upgrade head from empty DB.
    _run_alembic(["upgrade", "head"], pg_database_url)

    tables_after_upgrade = await _public_tables(pg_database_url)
    indexes_after_upgrade = await _public_indexes(pg_database_url)

    # The three Phase 6 tables should exist (alembic_version is the alembic
    # bookkeeping table — present any time alembic has run).
    assert {"user", "conversation", "message"} <= tables_after_upgrade, (
        f"Phase 6 tables missing after upgrade head: {tables_after_upgrade}"
    )
    assert "alembic_version" in tables_after_upgrade
    # D-02 mandatory composite unique index on (conversation_id, seq).
    assert "message_conv_seq" in indexes_after_upgrade, (
        f"message_conv_seq missing after upgrade head: {indexes_after_upgrade}"
    )

    # Step 2 — downgrade to base; the three Phase 6 tables should be gone.
    _run_alembic(["downgrade", "base"], pg_database_url)

    tables_after_downgrade = await _public_tables(pg_database_url)
    assert tables_after_downgrade.isdisjoint({"user", "conversation", "message"}), (
        f"Phase 6 tables still present after downgrade base: {tables_after_downgrade}"
    )
    # alembic_version stays — it's alembic's own bookkeeping, not part of D-02.
    assert "alembic_version" in tables_after_downgrade

    # Step 3 — upgrade head again; schema reappears.
    _run_alembic(["upgrade", "head"], pg_database_url)

    tables_after_reupgrade = await _public_tables(pg_database_url)
    indexes_after_reupgrade = await _public_indexes(pg_database_url)

    assert {"user", "conversation", "message"} <= tables_after_reupgrade
    assert "message_conv_seq" in indexes_after_reupgrade
